name: ITo-RuleBook
version: '1.0'
main: pl.polsatgranie.itomsd.ruleBook.RuleBook
api-version: '1.13'
load: STARTUP
authors: [ PolsatGraniePL ]
description: IToMSD plugin
website: https://itomsd.com/
commands:
  rbreload:
    description: Reloads the RuleBook plugin configuration
    permission: itomsd.rulebook.reload
    aliases:
      - rulebookreload
  acceptrules:
    description: Accepts the server rules
  denyrules:
    description: Denies the server rules